version: "3"
services:
  # app:
  #   platform: linux/x86_64
  #   build:
  #     context: node
  #   container_name: app
  #   networks:
  #     - node-network
  #   volumes:
  #     - ./node:/usr/src/app
  #   tty: true

  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodedb

    networks:
      - node-network

networks:
  node-network:
    driver: bridge
